### PR TITLE
Updated docs for release 0.2.1

### PR DESCRIPTION
**Pull request by jtniehof**
This is just the docs built from the same commit as spacepy/spacepy#215. It shouldn't be merged until that one is (so modifications can be made if necessary to do something about the release.)

### CODE REVIEW

**Comment by drsteve** [comment]
This was created with a much older version of Sphinx than last time... Is that expected? Or is it an environment change/regression?

**Comment by jtniehof** [comment]
Probably an issue of my home machine (last time) vs. my work machine (this time). Since the docs are also included in the source distribution, rebuilding them at home would involve redoing everything soup-to-nuts.

It does result in some annoying thrash in the repository but if it's otherwise working, I'd prefer to stick with this one this time...and then maybe we set up a consistent VM or something for doing the source release and doc builds in the future.

**Comment by drsteve** [comment]
Gotcha. Maybe have a build script with a conda environment?

**Comment by jtniehof** [comment]
Yes, a build script with a conda env would be a good idea.

**Pull request merged**
